spring:
  application:
    name: blog
  datasource:
    username: I543490
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/blog
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 50MB
project:
  folderPath: file/