spring:
  application:
    name: blog
  datasource:
    username: I543490
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/blog
  jpa:
    hibernate:
      ddl-auto: update